[package]
name = "teej-podcast-example-bridge"
version = "1.2.0"
authors = ["Dmitriy Kovalenko <dmtr.kovalenko@outlook.com>"]
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]
path = "./lib.rs"

[dependencies]
wasm-bindgen = "0.2.100"
fframes-editor-controller = { path = "../../../../fframes-editor-controller" }
teej_podcast_example = { path = "../../", default-features = false }

[lints]
workspace = true
