[package]
name = "webvtt-parser"
version = "1.2.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/dmtrKovalenko/fframes"
description = "WebVTT parser for Rust"
keywords = ["webvtt", "parser", "subtitle", "rust"]

[dependencies]
nom = "7.1.3"
nom_locate = "4.2.0"

[lints]
workspace = true
