[package]
name = "made-of-motion"
version = "1.2.0"
edition = "2024"
publish = false

[dependencies]
flate2 = "1"
fframes = { workspace = true, features = ["compile-time-svgtree", "cli"] }

[target.'cfg(target_os = "macos")'.dependencies]
fframes_skia_renderer = { workspace = true, features = ["metal"] }
fframes_native_player = { workspace = true, features = ["metal"] }

[target.'cfg(not(target_os = "macos"))'.dependencies]
fframes_skia_renderer = { workspace = true, features = ["vulkan"] }
fframes_native_player.workspace = true

[target.'cfg(not(windows))'.dependencies]
fframes = { workspace = true, features = ["h264", "libav-agree-gpl", "build-portable"] }

[lints]
workspace = true
