//! The reference edit, in its original 30000/1001 source-frame timebase.
//! Color hard cuts are individual shots; continuous camera moves stay inside a shot.
//! The integer-fps renderer produces these same 932 frames at 30 fps. The export
//! tool restores the rational timestamps and copies the reference AAC packets.

use crate::Effect;

pub(crate) const SOURCE_FRAMES: usize = 932;
pub(crate) const SOURCE_FPS_NUM: usize = 30000;
pub(crate) const SOURCE_FPS_DEN: usize = 1001;

#[derive(Clone, Copy, Debug)]
pub(crate) struct ShotSpec {
    pub name: &'static str,
    pub start: usize,
    pub end: usize,
    pub effect: Option<Effect>,
    pub variant: u8,
    pub clock_start: usize,
}

impl ShotSpec {
    pub const fn frames(self) -> usize {
        self.end - self.start
    }
}

pub(crate) const SHOTS: &[ShotSpec] = &[
    ShotSpec {
        name: "BlackLead",
        start: 0,
        end: 6,
        effect: None,
        variant: 0,
        clock_start: 0,
    },
    ShotSpec {
        name: "Boot",
        start: 6,
        end: 26,
        effect: Some(Effect::Binary),
        variant: 0,
        clock_start: 6,
    },
    ShotSpec {
        name: "Glass",
        start: 26,
        end: 57,
        effect: Some(Effect::Glass),
        variant: 0,
        clock_start: 26,
    },
    ShotSpec {
        name: "GlassAmber",
        start: 57,
        end: 82,
        effect: Some(Effect::Glass),
        variant: 1,
        clock_start: 26,
    },
    ShotSpec {
        name: "Chrome",
        start: 82,
        end: 91,
        effect: Some(Effect::Material),
        variant: 0,
        clock_start: 82,
    },
    ShotSpec {
        name: "Crystal",
        start: 91,
        end: 97,
        effect: Some(Effect::Material),
        variant: 4,
        clock_start: 82,
    },
    ShotSpec {
        name: "Gold",
        start: 97,
        end: 104,
        effect: Some(Effect::Material),
        variant: 1,
        clock_start: 82,
    },
    ShotSpec {
        name: "Ceramic",
        start: 104,
        end: 111,
        effect: Some(Effect::Material),
        variant: 5,
        clock_start: 82,
    },
    ShotSpec {
        name: "Carbon",
        start: 111,
        end: 119,
        effect: Some(Effect::Material),
        variant: 2,
        clock_start: 82,
    },
    ShotSpec {
        name: "ChromeSoft",
        start: 119,
        end: 126,
        effect: Some(Effect::Material),
        variant: 0,
        clock_start: 82,
    },
    ShotSpec {
        name: "Pixels",
        start: 126,
        end: 132,
        effect: Some(Effect::Material),
        variant: 3,
        clock_start: 82,
    },
    ShotSpec {
        name: "PrismGlass",
        start: 132,
        end: 141,
        effect: Some(Effect::Material),
        variant: 6,
        clock_start: 82,
    },
    ShotSpec {
        name: "OpenSource",
        start: 141,
        end: 209,
        effect: Some(Effect::LiquidChrome),
        variant: 0,
        clock_start: 141,
    },
    ShotSpec {
        name: "OpenSourceHold",
        start: 209,
        end: 222,
        effect: Some(Effect::LiquidChrome),
        variant: 0,
        clock_start: 141,
    },
    ShotSpec {
        name: "Rose",
        start: 222,
        end: 229,
        effect: Some(Effect::Obsidian),
        variant: 1,
        clock_start: 222,
    },
    ShotSpec {
        name: "Tunnel",
        start: 229,
        end: 238,
        effect: Some(Effect::Tunnel),
        variant: 0,
        clock_start: 229,
    },
    ShotSpec {
        name: "Halftone",
        start: 238,
        end: 256,
        effect: Some(Effect::Halftone),
        variant: 0,
        clock_start: 238,
    },
    ShotSpec {
        name: "ShaderLibrary",
        start: 256,
        end: 307,
        effect: Some(Effect::Catalog),
        variant: 0,
        clock_start: 256,
    },
    ShotSpec {
        name: "Gradient",
        start: 307,
        end: 344,
        effect: Some(Effect::Gradient),
        variant: 0,
        clock_start: 307,
    },
    ShotSpec {
        name: "Ascii",
        start: 344,
        end: 357,
        effect: Some(Effect::Ascii),
        variant: 1,
        clock_start: 344,
    },
    ShotSpec {
        name: "Particles",
        start: 357,
        end: 377,
        effect: Some(Effect::Particles),
        variant: 0,
        clock_start: 357,
    },
    ShotSpec {
        name: "Obsidian",
        start: 377,
        end: 391,
        effect: Some(Effect::Obsidian),
        variant: 0,
        clock_start: 377,
    },
    ShotSpec {
        name: "Silver",
        start: 391,
        end: 397,
        effect: Some(Effect::Spectral),
        variant: 2,
        clock_start: 391,
    },
    ShotSpec {
        name: "AuroraGreen",
        start: 397,
        end: 400,
        effect: Some(Effect::Aurora),
        variant: 1,
        clock_start: 391,
    },
    ShotSpec {
        name: "AuroraPurple",
        start: 400,
        end: 403,
        effect: Some(Effect::Aurora),
        variant: 2,
        clock_start: 391,
    },
    ShotSpec {
        name: "AuroraAqua",
        start: 403,
        end: 407,
        effect: Some(Effect::Aurora),
        variant: 3,
        clock_start: 391,
    },
    ShotSpec {
        name: "AuroraOrange",
        start: 407,
        end: 410,
        effect: Some(Effect::Aurora),
        variant: 4,
        clock_start: 391,
    },
    ShotSpec {
        name: "BlackBreak",
        start: 410,
        end: 417,
        effect: None,
        variant: 0,
        clock_start: 410,
    },
    ShotSpec {
        name: "Flow",
        start: 417,
        end: 447,
        effect: Some(Effect::Flow),
        variant: 0,
        clock_start: 417,
    },
    ShotSpec {
        name: "EmbossBlue",
        start: 447,
        end: 459,
        effect: Some(Effect::Emboss),
        variant: 0,
        clock_start: 447,
    },
    ShotSpec {
        name: "EmbossGreen",
        start: 459,
        end: 471,
        effect: Some(Effect::Emboss),
        variant: 1,
        clock_start: 447,
    },
    ShotSpec {
        name: "EmbossOrange",
        start: 471,
        end: 483,
        effect: Some(Effect::Emboss),
        variant: 2,
        clock_start: 447,
    },
    ShotSpec {
        name: "EmbossPearl",
        start: 483,
        end: 496,
        effect: Some(Effect::Emboss),
        variant: 3,
        clock_start: 447,
    },
    ShotSpec {
        name: "NativePreview",
        start: 496,
        end: 567,
        effect: Some(Effect::Preview),
        variant: 0,
        clock_start: 496,
    },
    ShotSpec {
        name: "ShaderModeEditor",
        start: 567,
        end: 586,
        effect: Some(Effect::Spectral),
        variant: 0,
        clock_start: 567,
    },
    ShotSpec {
        name: "ShaderModeZoom",
        start: 586,
        end: 610,
        effect: Some(Effect::Spectral),
        variant: 0,
        clock_start: 567,
    },
    ShotSpec {
        name: "ShaderMode",
        start: 610,
        end: 626,
        effect: Some(Effect::Spectral),
        variant: 0,
        clock_start: 567,
    },
    ShotSpec {
        name: "ShaderModeWide",
        start: 626,
        end: 640,
        effect: Some(Effect::Spectral),
        variant: 0,
        clock_start: 567,
    },
    ShotSpec {
        name: "BlackPause",
        start: 640,
        end: 654,
        effect: None,
        variant: 0,
        clock_start: 640,
    },
    ShotSpec {
        name: "Eclipse",
        start: 654,
        end: 849,
        effect: Some(Effect::Eclipse),
        variant: 0,
        clock_start: 654,
    },
    ShotSpec {
        name: "BlackTail",
        start: 849,
        end: 932,
        effect: None,
        variant: 0,
        clock_start: 849,
    },
];
