[package]
name = "cargo-fframes"
version = "1.2.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/dmtrKovalenko/fframes"
homepage = "https://fframes.studio"
description = "Creates new fframes video projects: `cargo fframes new my-video`"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
dialoguer = { version = "0.11", default-features = false }

[[bin]]
name = "cargo-fframes"
path = "src/main.rs"

[lints]
workspace = true
